//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPl3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class component_rating
    {
        public int id { get; set; }
        public Nullable<int> review_id { get; set; }
        public Nullable<int> component_id { get; set; }
        public string rating { get; set; }
    
        public virtual review_component review_component { get; set; }
        public virtual property_reviews property_reviews { get; set; }
    }
}
