//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPl3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dispute
    {
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> property_id { get; set; }
        public Nullable<int> booking_id { get; set; }
        public string title { get; set; }
        public string disputes_description { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<byte> disputes_status { get; set; }
    
        public virtual booking booking { get; set; }
        public virtual property property { get; set; }
        public virtual user user { get; set; }
    }
}
