//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPl3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emergency_contact
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string ec_name { get; set; }
        public string relationship { get; set; }
        public string ec_language { get; set; }
        public string email { get; set; }
        public string country { get; set; }
        public string phone_number { get; set; }
    
        public virtual user user { get; set; }
    }
}
