//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPl3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class governmentID
    {
        public int id { get; set; }
        public Nullable<int> userID { get; set; }
        public string driver_license { get; set; }
        public string passport { get; set; }
        public string identity_card { get; set; }
        public string backof_id_card { get; set; }
        public Nullable<System.DateTime> date_range { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public string number_card { get; set; }
    
        public virtual user user { get; set; }
    }
}
