//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPl3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class property_reviews
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public property_reviews()
        {
            this.component_rating = new HashSet<component_rating>();
        }
    
        public int id { get; set; }
        public Nullable<int> property_id { get; set; }
        public Nullable<int> review_by_user { get; set; }
        public Nullable<int> transaction_id { get; set; }
        public string comment { get; set; }
        public string overall_rating { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<byte> pr_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<component_rating> component_rating { get; set; }
        public virtual property property { get; set; }
        public virtual user user { get; set; }
        public virtual transaction transaction { get; set; }
    }
}
