//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPl3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public property()
        {
            this.bookings = new HashSet<booking>();
            this.disputes = new HashSet<dispute>();
            this.favourites = new HashSet<favourite>();
            this.neighbourhoods = new HashSet<neighbourhood>();
            this.property_amenities = new HashSet<property_amenities>();
            this.property_images = new HashSet<property_images>();
            this.property_reviews = new HashSet<property_reviews>();
            this.transactions = new HashSet<transaction>();
            this.properties_discounts = new HashSet<properties_discounts>();
        }
    
        public int id { get; set; }
        public string p_name { get; set; }
        public string p_description { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<byte> is_guest_favourite { get; set; }
        public Nullable<int> property_type_id { get; set; }
        public Nullable<int> room_type_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<int> state_id { get; set; }
        public Nullable<int> city_id { get; set; }
        public string p_address { get; set; }
        public string bedroom_count { get; set; }
        public string bed_count { get; set; }
        public string bathroom_count { get; set; }
        public string accomodates_count { get; set; }
        public string max_pets { get; set; }
        public Nullable<byte> availability_type { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> currency_id { get; set; }
        public Nullable<byte> price_type { get; set; }
        public string minimum_stay { get; set; }
        public Nullable<byte> minimum_stay_type { get; set; }
        public Nullable<byte> refund_type { get; set; }
        public Nullable<byte> booking_confirmation_method { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<byte> p_status { get; set; }
        public Nullable<byte> ask_for_booking { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> bookings { get; set; }
        public virtual city city { get; set; }
        public virtual country country { get; set; }
        public virtual currency currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dispute> disputes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favourite> favourites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<neighbourhood> neighbourhoods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<property_amenities> property_amenities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<property_images> property_images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<property_reviews> property_reviews { get; set; }
        public virtual property_type property_type { get; set; }
        public virtual room_type room_type { get; set; }
        public virtual state state { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction> transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<properties_discounts> properties_discounts { get; set; }
    }
}
