//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPl3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class property_images
    {
        public int id { get; set; }
        public Nullable<int> property_id { get; set; }
        public Nullable<int> added_by_user { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<byte> pi_status { get; set; }
        public string pi_image { get; set; }
    
        public virtual property property { get; set; }
        public virtual user user { get; set; }
    }
}
