//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPl3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_interests
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> interest_id { get; set; }
        public Nullable<byte> uitr_status { get; set; }
    
        public virtual interest interest { get; set; }
        public virtual user user { get; set; }
    }
}
