//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPl3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_personalInfor
    {
        public int id { get; set; }
        public Nullable<int> userID { get; set; }
        public string legal_name { get; set; }
        public string email_address { get; set; }
        public string facebook_id { get; set; }
        public string twitter_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public string street_address { get; set; }
        public Nullable<int> u_state { get; set; }
        public Nullable<int> u_city { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
    
        public virtual city city { get; set; }
        public virtual country country { get; set; }
        public virtual state state { get; set; }
        public virtual user user { get; set; }
    }
}
