//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPl3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_type_user_role
    {
        public int id { get; set; }
        public Nullable<byte> user_type_id { get; set; }
        public Nullable<int> user_role_id { get; set; }
    
        public virtual user_role user_role { get; set; }
        public virtual user_type user_type { get; set; }
    }
}
