//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPl3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_notification
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string content { get; set; }
        public Nullable<byte> un_status { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string un_url { get; set; }
    
        public virtual user user { get; set; }
    }
}
