//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPl3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_profile
    {
        public int id { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<byte> is_super_host { get; set; }
        public string user_work { get; set; }
        public string user_fun_fact { get; set; }
        public string user_favourite_song { get; set; }
        public string user_unless_skill { get; set; }
        public string user_pets { get; set; }
        public string user_school { get; set; }
        public string user_time_spend { get; set; }
        public string user_obsessed_with { get; set; }
        public string user_biography_title { get; set; }
        public string user_about { get; set; }
        public string user_avatar { get; set; }
        public Nullable<System.DateTime> user_birthday { get; set; }
    
        public virtual user user { get; set; }
    }
}
